  sudo: required
  language: python
  python:
    - "3.6"
    - "3.7-dev"
  install:
    - pip install -r requirements.txt
    - pip install --upgrade pytest
  script:
    - pytest -s -v --doctest-modules
  after_success:
    - coveralls
