{% set setup = load_setup_py_data() %}

package:
  name: bombard
  version: {{ setup.get('version') }}

source:
  path: .

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python
