# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    strategy:
      matrix:
        python-version: [3.9, "3.10", 3.11]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        echo ${{ runner.os }} ${{ matrix.os }}
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements.dev.txt
    - name: pre-commit
      if: runner.os == 'Linux'  # we do not need static code analizes on each OS, but we want to repeat it on Linux only for each Python version in matrix
      run: |
        pip install flake8 pylint pre-commit
        pre-commit run --all-files
    - name: Test with pytest and unittest
      run: |
        python -m unittest --verbose
        python -m pytest --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=bombard tests/ | tee pytest-coverage.txt
    - name: Pytest coverage comment
      if: ${{ matrix.python-version == 3.11 && matrix.platform == 'ubuntu-latest' }}
      uses: MishaKav/pytest-coverage-comment@main
      with:
        pytest-coverage-path: ./pytest-coverage.txt
        junitxml-path: ./pytest.xml
    - name: Upload coverage data to coveralls.io
      if: ${{ matrix.python-version == 3.11 && matrix.platform == 'ubuntu-latest' }}
      run: coveralls --service=github
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
